export default {
  popInDuration: 4000,
  bodyBGColor: '#f1f3f7',
  dollarColor: '#97A491',
  contentMarginHorizontal: '33px',
  contentMarginHorizontalDesktop: '8vw',
  baseFontSize: '16px',
  baseFontColor: 'rgb(38, 36, 36)',
  logoFontColor: '#444444',
  logoFontSize: '18px',
  linkColor: '#4f4f4f',
  linkFontSize: '0.9rem',
  productTitleColor: '#262626',
  productTitleBGColor: 'rgba(5, 2, 0, 0.7)',
  productTitleSize: 'calc(8vw + 1vh)',
  productTitleSizeMaxMobile: '7rem',
  productTitleSizeDesktop: 'calc(5vw + 5vh)',
  footerBg: '#141414',
  footerFontColor: '#B5B5B5',
  footerFontHighlightColor: '#E4E4E4',
  footerLogoFontColor: '#5A5A5A',
  quantityValueColor: '#666',
  quantityOperatorColor: '#ccc',
  quantityBorderColor: '#aaa',
  textboxFontColor: '#666'
}