export default {
  contentMarginHorizontal: '33px',
  contentMarginHorizontalDesktop: '8vw',
  baseFontSize: '16px',
  baseFontColor: '#292929',
  logoFontColor: '#444444',
  logoFontSize: '18px',
  linkColor: '#262626',
  productTitleColor: '#262626',
  productTitleSize: 'calc(14vw + 1vh)',
  productTitleSizeMaxMobile: '7rem',
  productTitleSizeDesktop: 'calc(5vw + 5vh)',
  footerBg: '#141414',
  footerFontColor: '#B5B5B5',
  footerFontHighlightColor: '#E4E4E4',
  footerLogoFontColor: '#5A5A5A',
  quantityValueColor: '#666',
  quantityOperatorColor: '#ccc',
  quantityBorderColor: '#aaa',
  textboxFontColor: '#666'
}